test:
  message: Hello from default

server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/orderdb
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  cloud:
    openfeign:
      circuitbreaker:
        enabled: false


resilience4j:  
  circuitbreaker:        
    instances:
      product-service:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 30000
        permitted-number-of-calls-in-half-open-state: 3
    configs:
      default:
        register-health-indicator: true 
management:
  health:
    circuitbreakers:
      enabled: true
         
